on: 
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 1 * *'
  workflow_call:
    secrets:
      CREDENTIALS:
        required: true
      ACCESS_TOKEN:
        required: true
jobs: 
  generate_data_job:
    runs-on: macos-latest
    uses: louismeunier/college-emails/.github/workflows/action.yml@latest
    secrets:
      CREDENTIALS: ${{ secrets.CREDENTIALS }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}