on: 
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 1 * *'
jobs: 
  generate_data_job:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: get and parse data
        working-directory: ./
        run: |
          pwd
          ls
          find scripts
          touch scripts/.env
          echo CREDENTIALS =${{ secrets.CREDENTIALS }} >> .env
          echo ACCESS_TOKEN =${{ secrets.ACCESS_TOKEN }} >> .env
          cd scripts && yarn && cd ..
          node scripts/index.js
        env:
          CREDENTIALS: ${{ secrets.CREDENTIALS }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}