on: 
  create
  schedule:
    - cron: '0 0 1 * *'
jobs: 
  generate_data_job:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: create & parse data locally
        working-directory: ./
        run: |
          pwd
          ls
          find scripts
          touch scripts/.env
          echo CREDENTIALS =${{ secrets.CREDENTIALS }} >> .env
          echo ACCESS_TOKEN =${{ secrets.ACCESS_TOKEN }} >> .env
          cd scripts && yarn && cd ..
          node scripts/index.js

          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A
          git commit -m "Update test.txt"
          git push
        env:
          CREDENTIALS: ${{ secrets.CREDENTIALS }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}