on: 
  push:
    tags:
      - '*'
  schedule:
    - cron: '0 0 1 * *'
jobs: 
  generate_data_job:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: create & parse data locally
        working-directory: ./
        run: |
          touch scripts/.env
          echo CREDENTIALS =${{ secrets.CREDENTIALS }} >> .env
          echo ACCESS_TOKEN =${{ secrets.ACCESS_TOKEN }} >> .env
          cd scripts && yarn && cd ..
          node scripts/index.js
        env:
          CREDENTIALS: ${{ secrets.CREDENTIALS }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -am "Update data"
          git push